### ISSUE TITLE
Doesn't work when many requests need to be made

### ISSUE THREAD

**Issue by hrustbb2** [centrifugal/phpcent#58] opened 2023-04-18 13:33 UTC
Doesn't work when many requests need to be made

**Comment by hrustbb2** [comment] 2023-05-25 20:37
ну чё там?

**Comment by FZambia** [comment] 2023-07-01 06:53
I am not able to reproduce the issue, added this test:

```php
    public function testPublishMultipleTimes()
    {
        for ($i = 0; $i < 5000; $i++) {
            $this->testPublish();
        }
    }
```

To [our test suite](https://github.com/centrifugal/phpcent/blob/master/tests/ClientTest.php) - and it works fine.

**Comment by aryzhkovg8** [comment] 2023-11-14 11:55
@hrustbb2 Can you provide больше деталей для reproduce этого бага?

**Comment by FZambia** [comment] 2024-04-07 11:15
Closing as can't reproduce.

**Closed by FZambia** 2024-04-07 11:15 UTC
